name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["MetOffice/208"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: linked-issues
    attributes:
      label: Are there any linked Issues or Pull Requests?
      description: Please tell us about any issues that might be associated with this bug or PRs that may be affected.
      placeholder: hello #&NoBreak;1 \# &#35; world
      #placeholder: hello&#x2060;world e.g. #&#x2060;12, MetOffice/Vernier#33
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - main
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
