blank_issues_enabled: false
contact_links:
  - name: LFRic Core community support
    url: https://github.com/MetOffice/simulation-systems/discussions/categories/lfric
    about: Please ask and answer questions here.